package com.ayulit.base;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/** It's a model class - it is been mapped to DB's table.
 *  Object of this class will table's ROW ! */
@Entity
@Table(name="fruits")
public class FruitORM {

	private int id;
	private String name;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY) // ID will be generated by DB engine (so this field must be created as autoincrement!)
	@Column(name="id")
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name="label")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public String toString() {
		return "FruitORM [id=" + id + ", name=" + name + "]";
	}
	
}
